# Generated by Django 4.1.1 on 2022-09-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
